### ISSUE TITLE
Plugin recommendation: folke/which-key.nvim

### ISSUE THREAD

**Issue by elkowar** [Olical/magic-kit#1]
Instead of liuchengxu/vim-which-key, i'd strongly recommend using https://github.com/folke/which-key.nvim
Reasons:
- Written and configured in lua - Lua API means nicer API in fennel in addition to the performance gains
- Support for mapping keys to functions directly - no more `<cmd>lua something()<cr>` on the right side of mappings
- Support for showing the contents of registers and marks directly
- Folke is super active, and all of his plugins are _amazing_ - Active and epic maintainers are always a plus

**Comment by Olical** [comment]
Ohh nice, good rec, thanks!
