### ISSUE TITLE
Windows errors with invalid string

### ISSUE THREAD

**Issue by zetashift** [Olical/magic-kit#3]
On a new Windows install, I installed neovim using `scoop` and put `magic-kit`'s `init.lua` in the `AppData` folder so neovim can load it. It errors out with:

```
 C:\Users\gebruiker\AppData\Local\nvim-data\site\pack\packer\start\aniseed\plugin\aniseed.vim:
line   2:
Parse error in C:/Users/gebruiker/AppData/Local/nvim/fnl\magic\init.fnl:1
  Invalid string: "C:/Users/gebruiker/AppData/Local/nvim/fnl\magic\init.fnl"
(module magic.init
-----------------------------------------------------------------------^
Parse error in C:/Users/gebruiker/AppData/Local/nvim/fnl\magic\keybindings.fnl:1
  Invalid string: "C:/Users/gebruiker/AppData/Local/nvim/fnl\magic\keybindings.fnl"
(module magic.keybindings
------------------------------------------------------------------------------^
E5108: Error executing lua ...a\site\pack\packer\start\aniseed\lua\aniseed\compile.lua:131: Could not open file: C:/Users/gebruiker/AppData/Local/nvim/lua\magic\macros.fnl: No such file or directory
```

Looking at the string it has to do with path handling but I thought that was solved with: https://github.com/Olical/aniseed/commit/ab8ef06e4619d6632d5cfb972c6588e962a82089

**Comment by Olical** [comment]
This _may_ be fixed on `develop` for Aniseed/Conjure, you should just have to reinstall / update your plugins. I've been adding OS aware path separators everywhere, maybe have missed some, but getting close. Or everything will work fine and I'm extremely lucky today.

**Comment by zetashift** [comment]
After some more testing, can confirm works fine!
